baseURL = "https://petercheng.net/"
title = "Peter Cheng"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
    description = "Peter Cheng's Website"
    dark = "auto"
    highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "photos"
    name = "photos"
    url = "/photos/"
    weight = 15

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.render]
  # Allows HTML in Markdown
  unsafe = true
