baseURL = "http://petercheng.net/"
languageCode = "en-us"
title = "Peter Cheng"
theme = "hyde-hyde"

[params]
    author = "Peter Cheng"
    authorimage = "https://raw.githubusercontent.com/petercheng00/personal/master/website/v2/petercheng/external_files/me.jpg"
    description = "Things about stuff"
    highlightjs = true
    highlightjsstyle = "zenburn"
    highlightjslanguages = ["lisp"]
[params.social]
    github = "petercheng00"
    linkedin = "petercheng00"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
